printf "%b\n" '\0047Hello'
printf "%b\n" '<\0047Hello'
printf "%b%b\n" '<' '%\0047Hello'
printf "%b%b\n" '<' '<\0047Hello'
printf "%b\n" '%\0047Hello'
printf "%b\n" '"Hello'
printf "%b\n" '<"Hello'
printf "%b%b\n" '<' '%"Hello'
printf "%b%b\n" '<' '<"Hello'
printf "%b\n" '%"Hello'
printf "%b\n" 'Hello \0047World\0047'
printf "%b\n" 'Hello "World"'
